language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - IMAGE_NAME="framework/piwik-log-analytics"

os:
- linux
services: docker
before_install:
  - "curl -H \"Authorization: token ${PP_GITHUB_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/PiwikPRO/Developers-Tools/contents/scripts/download-dtools.sh' | bash"

sudo: false

before_script:
  - ./tests/run_tests.sh
  - dtools dcr login --acr-only
  - docker build . -t ${IMAGE_NAME}

script:
  - dtools dcr push --image ${IMAGE_NAME} --dest-tag ${TRAVIS_TAG:-dev} --acr-only
